title: Nayantara Parpia
owner: Nayantara Parpia # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: "contact@nayantaraparpia.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nayantaraparpia.com" # the base hostname & protocol for your site
social:
  facebook-official: "https://facebook.com/nayantaraparpia"
  instagram: "https://www.instagram.com/nayantara_kathak/"
  linkedin-square: "https://sg.linkedin.com/in/nayantara-kurma-parpia-79197983"
  email: "mailto:contact@nayantaraparpia.com"
markdown: kramdown
collections:
  photo_gallery:
  


